# Generated by Django 5.0.7 on 2025-09-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
        ('reviews', '0002_reviewimage'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('user', 'medicine'), name='unique_user_medicine_review'),
        ),
    ]
