# Generated by Django 5.0.7 on 2025-09-28 10:10

import reviews.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_unique_user_medicine_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=reviews.models.review_image_path, verbose_name='Изображение'),
        ),
    ]
