# Generated by Django 5.0.7 on 2025-09-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grooming', '0002_groomingcenter_closed_at_groomingcenter_open_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groomingcenter',
            name='closed_at',
            field=models.TimeField(blank=True, verbose_name='Время закрытия'),
        ),
        migrations.AlterField(
            model_name='groomingcenter',
            name='open_at',
            field=models.TimeField(blank=True, verbose_name='Время открытия'),
        ),
    ]
