# Generated by Django 5.0.7 on 2025-10-03 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grooming', '0003_alter_groomingcenter_closed_at_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groomingcenter',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grooming_centers', to='users.userprofile'),
        ),
    ]
