# Generated by Django 5.2.5 on 2025-09-15 13:52

import clinics.models
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('address', models.CharField(max_length=500)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BY')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinics', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'Ветеринарная клиника',
                'verbose_name_plural': 'Ветеринарные клиники',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClinicService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to=clinics.models.clinic_service_main_image_path)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='clinics.clinic')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClinicServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=clinics.models.clinic_service_extra_image_path)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='clinics.clinicservice')),
            ],
        ),
        migrations.AddIndex(
            model_name='clinic',
            index=models.Index(fields=['name'], name='clinics_cli_name_b61e6f_idx'),
        ),
        migrations.AddIndex(
            model_name='clinic',
            index=models.Index(fields=['latitude', 'longitude'], name='clinics_cli_latitud_edfefe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clinic',
            unique_together={('name', 'address')},
        ),
        migrations.AddIndex(
            model_name='clinicservice',
            index=models.Index(fields=['name'], name='clinics_cli_name_61155c_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicservice',
            index=models.Index(fields=['clinic'], name='clinics_cli_clinic__239095_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clinicservice',
            unique_together={('clinic', 'slug')},
        ),
    ]
