# Generated by Django 5.2.5 on 2025-09-02 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='clinics.clinic'),
        ),
        migrations.AddIndex(
            model_name='clinic',
            index=models.Index(fields=['name'], name='clinics_cli_name_b61e6f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clinic',
            unique_together={('name', 'address')},
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['name'], name='clinics_ser_name_a0d2fe_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['clinic'], name='clinics_ser_clinic__c0a25a_idx'),
        ),
    ]
