# Generated by Django 5.2.5 on 2025-09-08 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicservice',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='clinics.clinic'),
        ),
        migrations.AddIndex(
            model_name='clinic',
            index=models.Index(fields=['name'], name='clinics_cli_name_b61e6f_idx'),
        ),
        migrations.AddIndex(
            model_name='clinic',
            index=models.Index(fields=['latitude', 'longitude'], name='clinics_cli_latitud_edfefe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clinic',
            unique_together={('name', 'address')},
        ),
        migrations.AddIndex(
            model_name='clinicservice',
            index=models.Index(fields=['name'], name='clinics_cli_name_61155c_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicservice',
            index=models.Index(fields=['clinic'], name='clinics_cli_clinic__239095_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clinicservice',
            unique_together={('clinic', 'slug')},
        ),
    ]
