# Generated by Django 5.0.7 on 2025-09-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_clinic_closed_at_clinic_open_at_clinic_work_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='closed_at',
            field=models.TimeField(blank=True, verbose_name='Время закрытия'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='open_at',
            field=models.TimeField(blank=True, verbose_name='Время открытия'),
        ),
    ]
