# Generated by Django 5.2.5 on 2025-09-02 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0001_initial'),
        ('pharmacies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pharmacymedicine',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_in_pharmacies', to='medicines.medicine'),
        ),
        migrations.AddField(
            model_name='pharmacymedicine',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_medicines', to='pharmacies.pharmacy'),
        ),
        migrations.AddIndex(
            model_name='pharmacy',
            index=models.Index(fields=['name'], name='pharmacies__name_0048a5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pharmacy',
            unique_together={('name', 'address')},
        ),
        migrations.AddIndex(
            model_name='pharmacymedicine',
            index=models.Index(fields=['medicine'], name='pharmacies__medicin_1fd6b6_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacymedicine',
            index=models.Index(fields=['pharmacy'], name='pharmacies__pharmac_bdb37e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pharmacymedicine',
            unique_together={('pharmacy', 'medicine')},
        ),
    ]
