# Generated by Django 5.0.7 on 2025-10-03 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0003_alter_pharmacy_closed_at_alter_pharmacy_open_at'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacies', to='users.userprofile'),
        ),
    ]
