# Generated by Django 5.2.5 on 2025-09-15 13:52

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='BY', unique=True, verbose_name='Телефон')),
                ('role', models.CharField(choices=[('admin_portal', 'Администратор портала'), ('client', 'Обычный пользователь'), ('pharmacy_admin', 'Администратор аптеки'), ('clinic_admin', 'Администратор клиники'), ('grooming_admin', 'Администратор груминг-центра')], db_index=True, default='client', max_length=24)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'indexes': [models.Index(fields=['role'], name='users_userp_role_c31a7e_idx')],
            },
        ),
    ]
