# Generated by Django 5.2.5 on 2025-09-15 13:52

import django.db.models.deletion
import medicines.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Слаг')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to=medicines.models.medicine_main_image_path)),
                ('manufacturer', models.CharField(blank=True, max_length=255, verbose_name='Производитель')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('instruction', models.TextField(blank=True, verbose_name='Инструкция по применению')),
                ('is_prescription', models.BooleanField(default=False, verbose_name='Требует рецепт')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='medicines.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Лекарство',
                'verbose_name_plural': 'Лекарства',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=medicines.models.medicine_extra_image_path)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='medicines.medicine')),
            ],
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['name'], name='medicines_m_name_61a774_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['slug'], name='medicines_m_slug_de8ca6_idx'),
        ),
    ]
