# Generated by Django 5.2.5 on 2025-09-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('category', models.CharField(choices=[('antibiotic', 'Антибиотик'), ('vaccine', 'Вакцина'), ('painkiller', 'Обезболивающее'), ('vitamin', 'Витамины'), ('other', 'Другое')], default='other', max_length=50)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('instruction', models.TextField(blank=True)),
                ('is_prescription', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Лекарство',
                'verbose_name_plural': 'Лекарства',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='medicines_m_name_61a774_idx'), models.Index(fields=['slug'], name='medicines_m_slug_de8ca6_idx')],
            },
        ),
    ]
