# Generated by Django 5.0.7 on 2025-09-30 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_address_order_customer_email_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_pharmac_447602_idx',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pharmacy',
        ),
    ]
