# Generated by Django 5.0.7 on 2025-09-30 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_orders_orde_pharmac_447602_idx_and_more'),
        ('pharmacies', '0003_alter_pharmacy_closed_at_alter_pharmacy_open_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpickup',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pharmacies.pharmacy'),
        ),
    ]
