# Generated by Django 5.0.7 on 2025-09-30 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderpickup_pharmacy'),
        ('pharmacies', '0003_alter_pharmacy_closed_at_alter_pharmacy_open_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderpickup',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='orderpickup',
            name='code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='orderpickup',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='orderpickup',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacies.pharmacy'),
        ),
        migrations.RemoveField(
            model_name='orderpickup',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='orderpickup',
            name='pickup_code',
        ),
    ]
