# Generated by Django 5.0.7 on 2025-10-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderpickup_unique_together_orderpickup_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpickup',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждён'), ('ready_for_pickup', 'Готов к выдаче'), ('cancelled', 'Отменён')], db_index=True, default='pending', max_length=32),
        ),
        migrations.AddField(
            model_name='orderpickup',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
