# Generated by Django 5.0.7 on 2025-10-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderpickup_status_orderpickup_status_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpickup',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждён'), ('ready_for_pickup', 'Готов к выдаче'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], db_index=True, default='pending', max_length=32),
        ),
    ]
