# Generated by Django 5.2.5 on 2025-09-08 20:40

import journal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='zip_file',
            field=models.FileField(blank=True, null=True, upload_to=journal.models.article_zip_path, verbose_name='ZIP архив со статьёй'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=journal.models.article_preview_path, verbose_name='Превью (для списка статей)'),
        ),
    ]
